version: '3'

services:
  miniprogram-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "cd /app/miniprogram && npm install && tail -f /dev/null"
    tty: true 